# Generated by Django 4.2.4 on 2023-08-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0002_rename_plant_soilmoisture_plant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilmoisture',
            name='title',
        ),
        migrations.RemoveField(
            model_name='waterlevel',
            name='title',
        ),
    ]
