# Generated by Django 4.2.4 on 2023-08-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0003_remove_soilmoisture_title_remove_waterlevel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterLevel',
        ),
    ]
