# Generated by Django 4.2.4 on 2023-08-26 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_remove_question_img'),
        ('apidevices', '0009_alter_waterplant_waterplant_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilmoisture',
            name='time',
        ),
        migrations.RemoveField(
            model_name='waterlevel',
            name='time',
        ),
        migrations.AddField(
            model_name='soilmoisture',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='waterplant',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LEDPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('waterplant_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.plant')),
            ],
        ),
    ]
