# Generated by Django 4.2.4 on 2023-08-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0010_remove_soilmoisture_time_remove_waterlevel_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledplant',
            old_name='waterplant_time',
            new_name='led_time',
        ),
    ]
