# Generated by Django 4.2.4 on 2023-09-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0011_rename_waterplant_time_ledplant_led_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledplant',
            name='status',
            field=models.CharField(default='ปิด', max_length=50),
        ),
        migrations.AlterField(
            model_name='waterplant',
            name='status',
            field=models.CharField(default='ปิด', max_length=50),
        ),
    ]
