# Generated by Django 4.2.4 on 2023-08-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0005_waterlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='waterlevel',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
