# Generated by Django 4.2.4 on 2023-08-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_remove_question_img'),
        ('apidevices', '0006_rename_plant_id_soilmoisture_plant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilmoisture',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='waterlevel',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.CreateModel(
            name='WaterPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.plant')),
            ],
        ),
    ]
