# Generated by Django 4.2.4 on 2023-08-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0007_rename_timestamp_soilmoisture_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterplant',
            old_name='time',
            new_name='waterplant_time',
        ),
    ]
