# Generated by Django 4.2.4 on 2023-10-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0012_alter_ledplant_status_alter_waterplant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledplant',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
