# Generated by Django 4.2.4 on 2023-10-21 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0033_article_article_img'),
        ('apidevices', '0013_alter_ledplant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('waterplant_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.plant')),
            ],
        ),
        migrations.DeleteModel(
            name='WaterPlant',
        ),
    ]
