# Generated by Django 4.2.4 on 2023-10-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0016_timec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilmoisture',
            name='soilmoisture',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='water_remaining',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True),
        ),
    ]
