# Generated by Django 4.2.4 on 2023-08-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_alter_profile_birthdate_alter_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='ยังไม่กำหนด', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
