# Generated by Django 4.2.4 on 2023-08-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_rename_plantmanager_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
