# Generated by Django 4.2.4 on 2023-08-28 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0024_question_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPasswordToken',
            new_name='ResetPasswordOTP',
        ),
    ]
