# Generated by Django 4.2.4 on 2023-10-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0026_alter_plant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='date',
            new_name='startdate',
        ),
        migrations.AddField(
            model_name='plant',
            name='enddate',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
