# Generated by Django 4.2.4 on 2023-10-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0036_remove_post_profile_remove_post_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile/default/user.png', null=True, upload_to='profile/'),
        ),
    ]
