# Generated by Django 4.2.4 on 2023-10-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0037_post_profile_post_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
