# Generated by Django 4.2.4 on 2023-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0038_remove_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile/default/user.png', null=True, upload_to='profile/'),
        ),
    ]
