# Generated by Django 4.2.1 on 2023-11-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0042_alter_plant_plant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_img',
            field=models.ImageField(blank=True, default='plant/default/plant.jpg', null=True, upload_to='plant/'),
        ),
    ]
