# Generated by Django 4.2.4 on 2023-08-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
