# Generated by Django 4.2.4 on 2023-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.CharField(default='ยังไม่กำหนด', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='ยังไม่กำหนด', max_length=100),
        ),
    ]
