# Generated by Django 4.2.4 on 2023-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_transaction_resetpasswordtoken_plantmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmanager',
            name='plant_img',
            field=models.ImageField(blank=True, default='plant/default/GreenOak.png', null=True, upload_to='plant/'),
        ),
    ]
