# Generated by Django 4.2.4 on 2023-08-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
