# Generated by Django 4.2.4 on 2023-08-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_remove_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
