# Generated by Django 4.2.4 on 2023-08-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_rename_question_id_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='time',
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
