# Generated by Django 4.2.1 on 2023-08-22 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidevices', '0006_rename_plant_id_soilmoisture_plant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0019_remove_answer_time_answer_date_answer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantManager',
            new_name='Plant',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plantstype',
            new_name='plantname',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
