# Generated by Django 4.2.4 on 2023-08-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_alter_answer_date_alter_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
