# Generated by Django 4.2.4 on 2023-08-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_remove_question_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
