# Generated by Django 4.2.4 on 2023-08-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0025_rename_resetpasswordtoken_resetpasswordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
