# Generated by Django 4.2.4 on 2023-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0027_rename_date_plant_startdate_plant_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='enddate',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='startdate',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
