# Generated by Django 4.2.4 on 2023-10-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0031_alter_article_detail_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='detail',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
