# Generated by Django 4.2.4 on 2023-10-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0035_post_name_post_profile_img_alter_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile_img',
        ),
    ]
