# Generated by Django 4.2.1 on 2023-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0039_comment_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='setendtime',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='setmoisture',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='setstarttime',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
