# Generated by Django 4.2.1 on 2023-11-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0040_plant_setendtime_plant_setmoisture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthdate',
            new_name='job',
        ),
    ]
