# Generated by Django 4.2.4 on 2024-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0043_alter_plant_plant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, default='-', null=True, upload_to='article/'),
        ),
    ]
